version: "2"
services:

  web:
    build:
      context: .
      dockerfile: container-build/web/Dockerfile
    container_name: my-laravel-server
    ports:
    - "8080:80"
    volumes:
    - .:/var/www/public
    depends_on:
    - db

  db:
    image: mysql:5.7
    environment:
    - MYSQL_HOST=db
    - MYSQL_ROOT_PASSWORD=secret
    - MYSQL_USER=homestead
    - MYSQL_PASSWORD=secret
    - MYSQL_DATABASE=homestead
    volumes:
      - mysql_data: /var/lib/mysql
  
  volumes:
    mysql_data: {driver: local}

