version: "2"
services:

  web:
    build:
      context: .
      dockerfile: container-build/web/Dockerfile
    environment:
    - MYSQL_DATABASE=homestead
    - MYSQL_USER=homestead
    - MYSQL_PASSWORD=secret
    - MYSQL_HOST=db
    ports:
    - "8080:80"
    volumes:
    - .:/var/www/public
    depends_on:
    - db

  db:
    image: mysql:5.7
    environment:
    - MYSQL_ROOT_PASSWORD=secret
    - MYSQL_USER=homestead
    - MYSQL_PASSWORD=secret
    - MYSQL_DATABASE=homestead

